### ISSUE TITLE
I couldn't apply because it always said that I need to fill skype field even I already did.

### ISSUE THREAD

**Issue by phanthehien** [nimbl3/our-team#9]
I tried to apply to 2 positions: Android Lead and iOS lead. But they are all failed.

Steps:
1. Open this link: https://www.workhiro.com/companies/nimbl3/f2ba33f7?locale=en
2. Fill all fields
3. click 'Apply for this job' button.

Result: See an error message:  Skype can't be blank

**Comment by olivierobert** [comment]
@phanthehien Thank you for notifying use of the issue! We really appreciate you took the time to raise this issue.

We have disabled the field for Skype so you should now be able to apply.

You can also apply directly by sending us an email [work@nimbl3.com](mailto:work@nimbl3.com)

Let me know if you need additional help.
